# Generated by Django 5.2.12 on 2026-03-26 16:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('location_text', models.CharField(blank=True, max_length=255)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='ILS', max_length=3)),
                ('registration_open', models.BooleanField(default=False)),
                ('public_roster_enabled', models.BooleanField(default=False)),
                ('morning_document_type', models.CharField(choices=[('305', 'Tax Invoice (305)'), ('320', 'Receipt (320)'), ('400', 'Receipt/Invoice (400)')], default='320', max_length=3)),
                ('cardcom_language', models.CharField(default='he', max_length=5)),
                ('landing_template', models.CharField(blank=True, help_text='Template override for landing page', max_length=120)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_at'],
            },
        ),
    ]
