# Generated by Django 5.2.12 on 2026-03-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['queue_name', 'status', 'available_at'], name='idx_job_dequeue'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_count__lte', models.F('max_attempts'))), name='attempts_lte_max_attempts'),
        ),
    ]
