# Generated by Django 5.2.12 on 2026-03-26 16:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('payments_cardcom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(default='morning', max_length=20)),
                ('document_type', models.CharField(blank=True, max_length=10)),
                ('vendor_document_id', models.CharField(blank=True, max_length=120)),
                ('document_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('created', 'Created'), ('emailed', 'Emailed'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('raw_response_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='applications.application')),
                ('payment_attempt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='document', to='payments_cardcom.paymentattempt')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
