# Generated by Django 5.2.12 on 2026-03-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('payments_cardcom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentattempt',
            name='currency',
            field=models.CharField(default='ILS', editable=False, max_length=3),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'ILS')), name='payment_attempt_currency_ils'),
        ),
    ]
