# Generated by Django 5.2.12 on 2026-03-26 16:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('public_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('answers_json', models.JSONField(blank=True, default=dict)),
                ('form_version', models.CharField(blank=True, max_length=50)),
                ('gm_status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='submitted', max_length=20)),
                ('payment_status', models.CharField(choices=[('not_requested', 'Not Requested'), ('link_created', 'Link Created'), ('link_sent', 'Link Sent'), ('paid', 'Paid'), ('failed', 'Failed'), ('expired', 'Expired'), ('waived', 'Waived')], db_index=True, default='not_requested', max_length=20)),
                ('invoice_status', models.CharField(choices=[('not_created', 'Not Created'), ('queued', 'Queued'), ('created', 'Created'), ('emailed', 'Emailed'), ('failed', 'Failed')], db_index=True, default='not_created', max_length=20)),
                ('is_publicly_published', models.BooleanField(default=False)),
                ('show_character_publicly', models.BooleanField(default=False)),
                ('show_faction_publicly', models.BooleanField(default=False)),
                ('public_character_name', models.CharField(blank=True, max_length=255)),
                ('public_faction_name', models.CharField(blank=True, max_length=255)),
                ('gm_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='public_site.event')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['event', 'gm_status'], name='application_event_i_bdb849_idx'), models.Index(fields=['event', 'is_publicly_published'], name='application_event_i_08e7cc_idx')],
            },
        ),
    ]
